name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Setup pnpm
        with:
          version: 9.11.0

      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
